version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passmebeta
      POSTGRES_DB: postgres

  user_app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:passmebeta@postgres:5432/postgres"
    depends_on:
      - postgres
    networks:
      - netOne

networks:
  netOne:
    driver: bridge
